### ISSUE TITLE
Build problem..

### ISSUE THREAD

**Issue by serhatgksu** [srdja/arp-poison#1]
Make command not run. 
make: **\* No targets specified and no makefile found.  Stop. write when i write make command. Please help me

**Comment by srdja** [comment]
Have you run `./autogen.sh` and then `./configure`?

edit1: I haven't looked at the project in a while and I've just realised how terrible the readme is. :( I'll add proper instructions to it.

edit2: and you also need `libpcap` to build it

edit3: you might also want to pull the latest commit if you get linker errors

If you have any more questions feel free to ask.
